### PR TITLE
Add support to generate book documents

### PR DESCRIPTION
**Pull request by otavio**
This adds support to generate book documents

The code has been reworked to allow a more easily addition of different document
types. As result, an initial version of book support has been included.

Signed-off-by: Otavio Salvador <otavio@ossystems.com.br>

### CODE REVIEW

**Comment by jirutka** [comment]
Thanks for your contribution!

@jxxcarlson, could you please review it?

**Comment by jxxcarlson** [comment]
I will this evening. Thank you!!

**Comment by otavio** [comment]
I have dropped the gemfile change and also included some more improvements.

**Comment by jxxcarlson** [comment]
These are excellent improvements to asciidoctor-latex.  Great to have another person working on the project.

**Comment by mojavelinux** [comment]
Nice work guys. Thanks for the contribution @otavio!

**Comment by mojavelinux** [comment]
> Great to have another person working on the project.

+1000

The LaTeX converter is a very important part of the AsciiDoc toolchain for many users, especially in the scientific community, so it's very exciting to see it advance so quickly! Keep up the great work. Also, encourage as many people to test it as you can hunt down. The more feedback we get, the better it will be. Open source FTW!

**Comment by jxxcarlson** [comment]
I am going to math meeting in San Antonio is a few days and will talk up Asciidoctor and
Asciidoctor-LaTeX there.  Not a public presentation, but leaning on my personal contacts.
I’d lke to get a few key people really loving it and giving us feedback before going wider.

**Pull request merged**
