### PR TITLE
Add support for bold text

### PR DESCRIPTION
**Pull request by blipp**
Convert `*example*` to `\textbf{example}`. For some reason, the code was present, but commented out. I adapted the tests as well. All tests that passed previously, still pass.

### CODE REVIEW

**Comment by edusantana** [comment]
I was needing the **bold** too, perhaps there's a reason it was *commented*.

We should use an other strategy to do **bolds**?

**Comment by blipp** [comment]
> I was needing the bold too, perhaps there's a reason it was commented.

Yes, probably there is a reason. Maybe @jxxcarlson knows it? At least there are a lot of tests, and the proposed change did not break random ones.

> We should use an other strategy to do bolds?

You can always use LaTeX syntax directly in your AsciiDoc file, although this is not really nice because it ties the document to LaTeX.

**Comment by jxxcarlson** [comment]
Tell me what you would like to have and I can probably take care of it tonight 
(Give me an example of the syntax)

**Comment by jxxcarlson** [comment]
I see -- you should certainly be able to do *this is really important*.

**Comment by jxxcarlson** [comment]
I must have goofed. Sorry about that!  Merged your pull request.

**Comment by edusantana** [comment]
thanks @jxxcarlson !

I'm trying to make it possible to write a *thesis* or *dissertation* with Asciidoc, without knowing Latex. It will use the [Brazilian latex template](https://github.com/abntex/abntex2/blob/master/doc/latex/abntex2/examples/abntex2-modelo-trabalho-academico.tex) behind the scenes.

**Comment by jxxcarlson** [comment]
Good luck!  Please let me know if you have problems.
Within the context of the project, I will do what I can
to help.

Jim

**Comment by blipp** [comment]
Thanks for merging, @jxxcarlson!

**Pull request merged**
