### PR TITLE
fix environment_literal block

### PR DESCRIPTION
**Pull request by mojavelinux**
- add environment_literal to list of node types
- add test for envv.equation

### CODE REVIEW

**Comment by jxxcarlson** [comment]
@mojavelinux This PR produces the correct html but (for me) produces empty tex output.  Try 
`bundle exec asciidoctor-latex -s bar.adoc` where `bar.adoc` is as below.
```
[envv.equation]
....
(a^2 + b^2)^2 = (a^2)^2 + 2a^2b^2 + (b^2)^2
....
```

**Comment by mojavelinux** [comment]
I noticed that. The problem is that environment_literal only seems to be mapped in the HTML converter. It never got a tex converter...at least I don't see it referenced anywhere. Are you sure this worked before?

**Comment by mojavelinux** [comment]
When an extension creates a block with a custom context, then there must be a converter method to match. Otherwise, the converter won't know how to handle the block.

**Comment by jxxcarlson** [comment]
Aha -- that is probably it. I am on a bus right now.  Will look at it when I get home.

**Pull request merged**
