### PR TITLE
Cross-compile to JavaScript

### PR DESCRIPTION
**Pull request by Mogztter**

### CODE REVIEW

**Comment by Mogztter** [comment]
Here are the following errors at runtime:

.1. TemplateConverter and ThreadSafe in Asciidoctor core: https://github.com/asciidoctor/asciidoctor/blob/master/lib/asciidoctor/converter/template.rb#L36


```javascript
  // ...
  self.$new(((($b = $opal.Object._scope.ThreadSafe) == null ? $opal.cm('ThreadSafe') : $b))._scope.Cache.$new())
} catch ($err) {if ($opal.$rescue($err, [(($b = $opal.Object._scope.LoadError) == null ? $opal.cm('LoadError') : $b)])) {
  self.$warn("asciidoctor: WARNING: gem 'thread_safe' is not installed. This gem recommended when registering custom converters.");
  self.$new();
} else { throw $err; }
```

The problem is that `Object::ThreadSafe` is unknown within the Opal context -> `Uncaught NameError: uninitialized constant Object::ThreadSafe`
To fix this issue I manually change the generated code into:

```javascript
  // ...
  return self.$new();
```

NOTE: I also added `return`, otherwise we the `self.$default()` is not instantiate -> `Uncaught TypeError: Cannot read property '$register' of undefined`

```javascript
return self.$default().$register(converter, backends);
```

.2.  `prepend` method not found: https://github.com/asciidoctor/asciidoctor-latex/blob/master/lib/asciidoctor/latex/converter.rb#L357

I don't know why but this trigger the following error -> `Uncaught TypeError: undefined is not a function`

```javascript
return self.$prepend((($scope.Asciidoctor)._scope.LaTeX)._scope.Html5ConverterExtensions)
```

`self` instance:
```javascript
OpalClass {_id: 98, _alloc: function, _isClass: true, constructor: function, _super: OpalClass…}__inc__: Array[0]__parent: OpalClass_alloc: function $Html5Converter(){}_base_module: OpalModule_id: 98_isClass: true_methods: Array[0]_name: "Html5Converter"_orig_scope: const_alloc_proto: Opal.boot.ctor_scope: const_alloc_super: OpalClassconstructor: function OpalClass() {}__proto__: mtor
```

@jxxcarlson @mojavelinux I didn't find any reference of the  `prepend` method in Asciidoctor core or Asciidoctor latex ?

**Comment by jxxcarlson** [comment]
Wow, that was fast!

I merged, pulled, and pushed some small changes, the most significant of which
are just changes to README.adoc.

Use 
```
	$ asciidotor-latex -b html README.adoc 
```
to compile it to HTML. This will be a good test
file for the Chrome extension.  See the try-out directory for others.

When I do 
```
	$ rake -f cross.rake
```
I get this again:
```
	$ rake -f cross.rake 
	rake aborted!
	NameError: uninitialized constant Opal::Environment
	/Users/carlson/dev/git/asciidoctor-latex/cross.rake:17:in `block in <top (required)>'
	Tasks: TOP => default => dist
```
The directory `rake` is as follows:
```
$ ls rake
cacert.pem	jdk_helper.rb	tar-licence	tar.rb
```

I will get a VPN connection in Beijing so as to try this out on the Chrome extension
when you get there.  All things Google are blocked here.  Aaarrgh!!!

===================
PS.

The prepend method is something that Dan taught me.   It is used in `converter.rb`:

```
class Asciidoctor::Converter::Html5Converter
  # inject our custom code into the existing Html5Converter class (Ruby 2.0 and above)
  prepend Asciidoctor::LaTeX::Html5ConverterExtensions
end
```

**Comment by jxxcarlson** [comment]
I forgot to ask.  Is there a command-line way of testing Asciidoctor.js?

How should I best go about testing it?

**Comment by Mogztter** [comment]
> I get this again:
> ```
> $ rake -f cross.rake
> rake aborted!
> NameError: uninitialized constant Opal::Environment
> /Users/carlson/dev/git/asciidoctor-latex/cross.rake:17:in `block in <top (required)>'
> Tasks: TOP => default => dist
> ```

You need to run `bundle install` to install Opal gem in asciidoctor-latex project.

> The directory `rake` is as follows:
> ```
> $ ls rake
> cacert.pem	jdk_helper.rb	tar-licence	tar.rb
> ```

I removed the `require` on jdk_helper.rb and `tar.rb` because we don't need those classes. The `rake` directory can be safely removed.

> I will get a VPN connection in Beijing so as to try this out on the Chrome extension
when you get there.  All things Google are blocked here.  Aaarrgh!!!

Ah China... Hopefully GitHub is still up and running over there :wink:
http://arstechnica.com/security/2015/04/ddos-attacks-that-crippled-github-linked-to-great-firewall-of-china/

> The prepend method is something that Dan taught me.   It is used in `converter.rb`:
> ```
> class Asciidoctor::Converter::Html5Converter
>  # inject our custom code into the existing Html5Converter class (Ruby 2.0 and above)
>  prepend Asciidoctor::LaTeX::Html5ConverterExtensions
> end
> ```

Yes but I can't find the definition of this prepend method ? Was this method removed ?

> I forgot to ask.  Is there a command-line way of testing Asciidoctor.js?
> How should I best go about testing it?

I'm working on an Asciidoctor.js CLI https://github.com/asciidoctor/asciidoctor.js/pull/89
But for now I don't have a simple way to do testing. Plus errors are hard to understand :disappointed:

**Comment by jxxcarlson** [comment]
> 
> Yes but I can't find the definition of this prepend method ? Was this method removed ?

Hmm… Asciidoctor-latex depends pretty heavily on it.  I build the gem locally fairly often, so it must be there some place:-))).  Better ask Dan aka @mojavelinux :-)

I forgot to mention that to install the asciidoctor-latex gem locally, run `rake install`.
Jakub @jirultka set this up for me. — But I don’t see the relevant definition in the Rakefile!?!

**Comment by jxxcarlson** [comment]
I believe that this is it:

	http://dev.af83.com/2012/10/19/ruby-2-0-module-prepend.html <http://dev.af83.com/2012/10/19/ruby-2-0-module-prepend.html>

But Dan will know for sure.

**Comment by Mogztter** [comment]
Hmm it's a language feature introduced in Ruby 2.0... Maybe Opal doesn't
have it yet. I will ask them to be sure.

Thanks.

**Comment by jxxcarlson** [comment]
I think prepend is not in the current Opal.  I tried the below using the code from

	http://dev.af83.com/2012/10/19/ruby-2-0-module-prepend.html 

Is the error message in (2) the one that you saw?  Is there a way of getting prepend into Opal.

*The example:*

(1) Paste the example into a file.

```
 cd /tmp

$ cat >foo.rb

module FooBar
  def hello
    puts 2
    super
  end
end

class Foo
  def hello
    puts 'hello'
  end
end

class Bar < Foo
  prepend FooBar

  def hello
    puts 1
    super
  end
end

Bar.new.hello
```

(2) Run opal on the fie

```
$ opal foo.rb

/private/var/folders/2p/f989tv8n3kx8xqwhvrr3t0ym0000gn/T/opal-nodejs-runner-20150414-30422-xk04b0:3041
      throw exception;
            ^
NoMethodError: undefined method `prepend' for Bar
    at OpalClass.$new (/private/var/folders/2p/f989tv8n3kx8xqwhvrr3t0ym0000gn/T/opal-nodejs-runner-20150414-30422-xk04b0:3361:15)
    at OpalClass.<anonymous> (/private/var/folders/2p/f989tv8n3kx8xqwhvrr3t0ym0000gn/T/opal-nodejs-runner-20150414-30422-xk04b0:3037:31)
    at OpalClass.Opal.defn.TMP_1 (/private/var/folders/2p/f989tv8n3kx8xqwhvrr3t0ym0000gn/T/opal-nodejs-runner-20150414-30422-xk04b0:2440:19)
    at OpalClass.method_missing_stub [as $prepend] (/private/var/folders/2p/f989tv8n3kx8xqwhvrr3t0ym0000gn/T/opal-nodejs-runner-20150414-30422-xk04b0:709:35)
    at /private/var/folders/2p/f989tv8n3kx8xqwhvrr3t0ym0000gn/T/opal-nodejs-runner-20150414-30422-xk04b0:12926:10
    at /private/var/folders/2p/f989tv8n3kx8xqwhvrr3t0ym0000gn/T/opal-nodejs-runner-20150414-30422-xk04b0:12935:5
    at Object.<anonymous> (/private/var/folders/2p/f989tv8n3kx8xqwhvrr3t0ym0000gn/T/opal-nodejs-runner-20150414-30422-xk04b0:12937:3)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)

```


http://noteshare.io
http://home.noteshareblog.io

**Comment by Mogztter** [comment]
I think that the same issue but I'm running using the Opal JavaScript runtime.
Could you open an issue in the Opal repository with your sample code ?

**Comment by jxxcarlson** [comment]
Done!:

https://github.com/opal/opal/issues/796 <https://github.com/opal/opal/issues/796>

**Comment by jxxcarlson** [comment]
Filed an issue and got this reply:

	https://github.com/opal/opal/issues/796#issuecomment-92781943 <https://github.com/opal/opal/issues/796#issuecomment-92781943>

The developer will try to get prepend into 0.8.  Meanwhile, I’ve forked the repo
and am trying to understand Adam’s comment to see if there is an interim hack/solution.
This is about five levels above my expertise, so feel free to do likewise!  For now I am just poking around).

Jim

http://noteshare.io <http://noteshare.io/>
http://home.noteshareblog.io <http://home.noteshareblog.io/>

**Comment by Mogztter** [comment]
> This is about five levels above my expertise, so feel free to do likewise!  For now I am just poking around

Aha aha but if you succeeded on your own you will become Opal Ninja! :godmode:

**Comment by jxxcarlson** [comment]
I ran across chart-block-mace  in extensions-lab but can’t figure out how to use it?
Could you point the way?

Jim

http://noteshare.io <http://noteshare.io/>
http://home.noteshareblog.io <http://home.noteshareblog.io/>

**Pull request merged**
